// =============================
// CHARACTER DATA
// =============================

// Reine Datenlisten pro Set. Die Logik dazu steht in characters.js.

const disneyCharacters = [
  {
    id: 1,
    name: "Aladdin",
    image: "src/disney/aladdin.avif",

    human: true,
    female: false,
    male: true,
    animal: false,
    hasHair: true,
    canFly: false,
    pixar: false,
    royal: false,
    hasWings: false,
    wearsHat: false,
    hasFur: false,
    waterRelated: false,
    magicalCreature: false,

    blackHair: true,
    brownHair: false,
    blondeHair: false,
    redHair: false,
    wearsRed: false,
    wearsBlue: false,
    wearsGreen: false,
    wearsDress: false,
  },

  {
    id: 2,
    name: "Ariel",
    image: "src/disney/ariel.avif",

    human: true,
    female: true,
    male: false,
    animal: false,
    hasHair: true,
    canFly: false,
    pixar: false,
    royal: true,
    hasWings: false,
    wearsHat: false,
    hasFur: false,
    waterRelated: true,
    magicalCreature: true,

    blackHair: false,
    brownHair: false,
    blondeHair: false,
    redHair: true,
    wearsRed: false,
    wearsBlue: false,
    wearsGreen: true,
    wearsDress: false,
  },

  {
    id: 3,
    name: "Bambi",
    image: "src/disney/bambi.avif",

    human: false,
    female: false,
    male: true,
    animal: true,
    hasHair: false,
    canFly: false,
    pixar: false,
    royal: false,
    hasWings: false,
    wearsHat: false,
    hasFur: true,
    waterRelated: false,
    magicalCreature: false,

    blackHair: false,
    brownHair: false,
    blondeHair: false,
    redHair: false,
    wearsRed: false,
    wearsBlue: false,
    wearsGreen: false,
    wearsDress: false,
  },

  {
    id: 4,
    name: "Cinderella",
    image: "src/disney/cinderella.avif",

    human: true,
    female: true,
    male: false,
    animal: false,
    hasHair: true,
    canFly: false,
    pixar: false,
    royal: true,
    hasWings: false,
    wearsHat: false,
    hasFur: false,
    waterRelated: false,
    magicalCreature: false,

    blackHair: false,
    brownHair: false,
    blondeHair: true,
    redHair: false,
    wearsRed: false,
    wearsBlue: true,
    wearsGreen: false,
    wearsDress: true,
  },

  {
    id: 5,
    name: "Donald Duck",
    image: "src/disney/donald_duck.avif",

    human: false,
    female: false,
    male: true,
    animal: true,
    hasHair: false,
    canFly: true,
    pixar: false,
    royal: false,
    hasWings: true,
    wearsHat: true,
    hasFur: false,
    waterRelated: true,
    magicalCreature: false,

    blackHair: false,
    brownHair: false,
    blondeHair: false,
    redHair: false,
    wearsRed: false,
    wearsBlue: true,
    wearsGreen: false,
    wearsDress: false,
  },

  {
    id: 6,
    name: "Dumbo",
    image: "src/disney/dumbo.avif",

    human: false,
    female: false,
    male: true,
    animal: true,
    hasHair: false,
    canFly: true,
    pixar: false,
    royal: false,
    hasWings: false,
    wearsHat: false,
    hasFur: false,
    waterRelated: false,
    magicalCreature: false,

    blackHair: false,
    brownHair: false,
    blondeHair: false,
    redHair: false,
    wearsRed: false,
    wearsBlue: false,
    wearsGreen: false,
    wearsDress: false,
  },

  {
    id: 7,
    name: "Goofy",
    image: "src/disney/goofy.avif",

    human: false,
    female: false,
    male: true,
    animal: true,
    hasHair: false,
    canFly: false,
    pixar: false,
    royal: false,
    hasWings: false,
    wearsHat: true,
    hasFur: true,
    waterRelated: false,
    magicalCreature: false,

    blackHair: false,
    brownHair: false,
    blondeHair: false,
    redHair: false,
    wearsRed: false,
    wearsBlue: false,
    wearsGreen: true,
    wearsDress: false,
  },

  {
    id: 8,
    name: "Hercules",
    image: "src/disney/hercules.avif",

    human: true,
    female: false,
    male: true,
    animal: false,
    hasHair: true,
    canFly: false,
    pixar: false,
    royal: false,
    hasWings: false,
    wearsHat: false,
    hasFur: false,
    waterRelated: false,
    magicalCreature: false,

    blackHair: false,
    brownHair: true,
    blondeHair: false,
    redHair: false,
    wearsRed: false,
    wearsBlue: false,
    wearsGreen: false,
    wearsDress: false,
  },

  {
    id: 9,
    name: "Lightning McQueen",
    image: "src/disney/lightning_mcqueen.avif",

    human: false,
    female: false,
    male: true,
    animal: false,
    hasHair: false,
    canFly: false,
    pixar: true,
    royal: false,
    hasWings: false,
    wearsHat: false,
    hasFur: false,
    waterRelated: false,
    magicalCreature: false,

    blackHair: false,
    brownHair: false,
    blondeHair: false,
    redHair: false,
    wearsRed: true,
    wearsBlue: false,
    wearsGreen: false,
    wearsDress: false,
  },

  {
    id: 10,
    name: "Merida",
    image: "src/disney/merida.avif",

    human: true,
    female: true,
    male: false,
    animal: false,
    hasHair: true,
    canFly: false,
    pixar: true,
    royal: true,
    hasWings: false,
    wearsHat: false,
    hasFur: false,
    waterRelated: false,
    magicalCreature: false,

    blackHair: false,
    brownHair: false,
    blondeHair: false,
    redHair: true,
    wearsRed: false,
    wearsBlue: false,
    wearsGreen: true,
    wearsDress: true,
  },

  {
    id: 11,
    name: "Mickey Mouse",
    image: "src/disney/mickey_mouse.avif",

    human: false,
    female: false,
    male: true,
    animal: true,
    hasHair: false,
    canFly: false,
    pixar: false,
    royal: false,
    hasWings: false,
    wearsHat: false,
    hasFur: true,
    waterRelated: false,
    magicalCreature: false,

    blackHair: false,
    brownHair: false,
    blondeHair: false,
    redHair: false,
    wearsRed: true,
    wearsBlue: false,
    wearsGreen: false,
    wearsDress: false,
  },

  {
    id: 12,
    name: "Mike",
    image: "src/disney/mike.avif",

    human: false,
    female: false,
    male: true,
    animal: false,
    hasHair: false,
    canFly: false,
    pixar: true,
    royal: false,
    hasWings: false,
    wearsHat: false,
    hasFur: false,
    waterRelated: false,
    magicalCreature: true,

    blackHair: false,
    brownHair: false,
    blondeHair: false,
    redHair: false,
    wearsRed: false,
    wearsBlue: false,
    wearsGreen: true,
    wearsDress: false,
  },

  {
    id: 13,
    name: "Moana",
    image: "src/disney/moana.avif",

    human: true,
    female: true,
    male: false,
    animal: false,
    hasHair: true,
    canFly: false,
    pixar: false,
    royal: false,
    hasWings: false,
    wearsHat: false,
    hasFur: false,
    waterRelated: true,
    magicalCreature: false,

    blackHair: false,
    brownHair: true,
    blondeHair: false,
    redHair: false,
    wearsRed: true,
    wearsBlue: false,
    wearsGreen: false,
    wearsDress: true,
  },

  {
    id: 14,
    name: "Olaf",
    image: "src/disney/olaf.avif",

    human: false,
    female: false,
    male: true,
    animal: false,
    hasHair: false,
    canFly: false,
    pixar: false,
    royal: false,
    hasWings: false,
    wearsHat: false,
    hasFur: false,
    waterRelated: true,
    magicalCreature: true,

    blackHair: false,
    brownHair: false,
    blondeHair: false,
    redHair: false,
    wearsRed: false,
    wearsBlue: false,
    wearsGreen: false,
    wearsDress: false,
  },

  {
    id: 15,
    name: "Pinocchio",
    image: "src/disney/pinocchio.avif",

    human: false,
    female: false,
    male: true,
    animal: false,
    hasHair: true,
    canFly: false,
    pixar: false,
    royal: false,
    hasWings: false,
    wearsHat: true,
    hasFur: false,
    waterRelated: false,
    magicalCreature: true,

    blackHair: true,
    brownHair: false,
    blondeHair: false,
    redHair: false,
    wearsRed: true,
    wearsBlue: false,
    wearsGreen: false,
    wearsDress: false,
  },

  {
    id: 16,
    name: "Stitch",
    image: "src/disney/stitch.avif",

    human: false,
    female: false,
    male: true,
    animal: false,
    hasHair: false,
    canFly: false,
    pixar: false,
    royal: false,
    hasWings: false,
    wearsHat: false,
    hasFur: true,
    waterRelated: false,
    magicalCreature: true,

    blackHair: false,
    brownHair: false,
    blondeHair: false,
    redHair: false,
    wearsRed: false,
    wearsBlue: true,
    wearsGreen: false,
    wearsDress: false,
  },

  {
    id: 17,
    name: "Tinker Bell",
    image: "src/disney/tinker_bell.avif",

    human: true,
    female: true,
    male: false,
    animal: false,
    hasHair: true,
    canFly: true,
    pixar: false,
    royal: false,
    hasWings: true,
    wearsHat: false,
    hasFur: false,
    waterRelated: false,
    magicalCreature: true,

    blackHair: false,
    brownHair: false,
    blondeHair: true,
    redHair: false,
    wearsRed: false,
    wearsBlue: false,
    wearsGreen: true,
    wearsDress: true,
  },

  {
    id: 18,
    name: "Winnie The Pooh",
    image: "src/disney/winnie_the_pooh.avif",

    human: false,
    female: false,
    male: true,
    animal: true,
    hasHair: false,
    canFly: false,
    pixar: false,
    royal: false,
    hasWings: false,
    wearsHat: false,
    hasFur: true,
    waterRelated: false,
    magicalCreature: false,

    blackHair: false,
    brownHair: false,
    blondeHair: false,
    redHair: false,
    wearsRed: true,
    wearsBlue: false,
    wearsGreen: false,
    wearsDress: false,
  },
];

const animalsCharacters = [
  {
    id: 1,
    name: "Giraffe",
    image: "src/animals/giraffe.jpg",

    mammal: true,
    bird: false,
    reptile: false,
    fish: false,
    hasFur: true,
    hasWings: false,
    canFly: false,
    livesInWater: false,
    fourLegs: true,
    hasTail: true,
    hasHorns: true,
    dangerous: false,
    domestic: false,

    largeAnimal: true,
    hasStripes: false,
    hasSpots: true,
    hasLongEars: false,
    hasLongNeck: true,
  },

  {
    id: 2,
    name: "Lion",
    image: "src/animals/lion.jpg",

    mammal: true,
    bird: false,
    reptile: false,
    fish: false,
    hasFur: true,
    hasWings: false,
    canFly: false,
    livesInWater: false,
    fourLegs: true,
    hasTail: true,
    hasHorns: false,
    dangerous: true,
    domestic: false,

    largeAnimal: true,
    hasStripes: false,
    hasSpots: false,
    hasLongEars: false,
    hasLongNeck: false,
  },

  {
    id: 3,
    name: "Elephant",
    image: "src/animals/elephant.jpg",

    mammal: true,
    bird: false,
    reptile: false,
    fish: false,
    hasFur: false,
    hasWings: false,
    canFly: false,
    livesInWater: false,
    fourLegs: true,
    hasTail: true,
    hasHorns: false,
    dangerous: true,
    domestic: false,

    largeAnimal: true,
    hasStripes: false,
    hasSpots: false,
    hasLongEars: true,
    hasLongNeck: false,
  },

  {
    id: 4,
    name: "Tiger",
    image: "src/animals/tiger.jpg",

    mammal: true,
    bird: false,
    reptile: false,
    fish: false,
    hasFur: true,
    hasWings: false,
    canFly: false,
    livesInWater: false,
    fourLegs: true,
    hasTail: true,
    hasHorns: false,
    dangerous: true,
    domestic: false,

    largeAnimal: true,
    hasStripes: true,
    hasSpots: false,
    hasLongEars: false,
    hasLongNeck: false,
  },

  {
    id: 5,
    name: "Zebra",
    image: "src/animals/zebra.jpg",

    mammal: true,
    bird: false,
    reptile: false,
    fish: false,
    hasFur: true,
    hasWings: false,
    canFly: false,
    livesInWater: false,
    fourLegs: true,
    hasTail: true,
    hasHorns: false,
    dangerous: false,
    domestic: false,

    largeAnimal: true,
    hasStripes: true,
    hasSpots: false,
    hasLongEars: false,
    hasLongNeck: false,
  },

  {
    id: 6,
    name: "Monkey",
    image: "src/animals/monkey.jpg",

    mammal: true,
    bird: false,
    reptile: false,
    fish: false,
    hasFur: true,
    hasWings: false,
    canFly: false,
    livesInWater: false,
    fourLegs: false,
    hasTail: true,
    hasHorns: false,
    dangerous: false,
    domestic: false,

    largeAnimal: false,
    hasStripes: false,
    hasSpots: false,
    hasLongEars: false,
    hasLongNeck: false,
  },

  {
    id: 7,
    name: "Dog",
    image: "src/animals/dog.jpg",

    mammal: true,
    bird: false,
    reptile: false,
    fish: false,
    hasFur: true,
    hasWings: false,
    canFly: false,
    livesInWater: false,
    fourLegs: true,
    hasTail: true,
    hasHorns: false,
    dangerous: false,
    domestic: true,

    largeAnimal: false,
    hasStripes: false,
    hasSpots: false,
    hasLongEars: false,
    hasLongNeck: false,
  },

  {
    id: 8,
    name: "Cat",
    image: "src/animals/cat.jpg",

    mammal: true,
    bird: false,
    reptile: false,
    fish: false,
    hasFur: true,
    hasWings: false,
    canFly: false,
    livesInWater: false,
    fourLegs: true,
    hasTail: true,
    hasHorns: false,
    dangerous: false,
    domestic: true,

    largeAnimal: false,
    hasStripes: false,
    hasSpots: false,
    hasLongEars: false,
    hasLongNeck: false,
  },

  {
    id: 9,
    name: "Rabbit",
    image: "src/animals/rabbit.jpg",

    mammal: true,
    bird: false,
    reptile: false,
    fish: false,
    hasFur: true,
    hasWings: false,
    canFly: false,
    livesInWater: false,
    fourLegs: true,
    hasTail: true,
    hasHorns: false,
    dangerous: false,
    domestic: true,

    largeAnimal: false,
    hasStripes: false,
    hasSpots: false,
    hasLongEars: true,
    hasLongNeck: false,
  },

  {
    id: 10,
    name: "Cow",
    image: "src/animals/cow.jpg",

    mammal: true,
    bird: false,
    reptile: false,
    fish: false,
    hasFur: true,
    hasWings: false,
    canFly: false,
    livesInWater: false,
    fourLegs: true,
    hasTail: true,
    hasHorns: true,
    dangerous: false,
    domestic: true,

    largeAnimal: true,
    hasStripes: false,
    hasSpots: true,
    hasLongEars: false,
    hasLongNeck: false,
  },

  {
    id: 11,
    name: "Horse",
    image: "src/animals/horse.jpg",

    mammal: true,
    bird: false,
    reptile: false,
    fish: false,
    hasFur: true,
    hasWings: false,
    canFly: false,
    livesInWater: false,
    fourLegs: true,
    hasTail: true,
    hasHorns: false,
    dangerous: false,
    domestic: true,

    largeAnimal: true,
    hasStripes: false,
    hasSpots: false,
    hasLongEars: false,
    hasLongNeck: false,
  },

  {
    id: 12,
    name: "Penguin",
    image: "src/animals/penguin.jpg",

    mammal: false,
    bird: true,
    reptile: false,
    fish: false,
    hasFur: false,
    hasWings: true,
    canFly: false,
    livesInWater: true,
    fourLegs: false,
    hasTail: true,
    hasHorns: false,
    dangerous: false,
    domestic: false,

    largeAnimal: false,
    hasStripes: false,
    hasSpots: false,
    hasLongEars: false,
    hasLongNeck: false,
  },

  {
    id: 13,
    name: "Eagle",
    image: "src/animals/eagle.jpg",

    mammal: false,
    bird: true,
    reptile: false,
    fish: false,
    hasFur: false,
    hasWings: true,
    canFly: true,
    livesInWater: false,
    fourLegs: false,
    hasTail: true,
    hasHorns: false,
    dangerous: true,
    domestic: false,

    largeAnimal: false,
    hasStripes: false,
    hasSpots: false,
    hasLongEars: false,
    hasLongNeck: false,
  },

  {
    id: 14,
    name: "Crocodile",
    image: "src/animals/crocodile.jpg",

    mammal: false,
    bird: false,
    reptile: true,
    fish: false,
    hasFur: false,
    hasWings: false,
    canFly: false,
    livesInWater: true,
    fourLegs: true,
    hasTail: true,
    hasHorns: false,
    dangerous: true,
    domestic: false,

    largeAnimal: true,
    hasStripes: false,
    hasSpots: false,
    hasLongEars: false,
    hasLongNeck: false,
  },

  {
    id: 15,
    name: "Snake",
    image: "src/animals/snake.jpg",

    mammal: false,
    bird: false,
    reptile: true,
    fish: false,
    hasFur: false,
    hasWings: false,
    canFly: false,
    livesInWater: false,
    fourLegs: false,
    hasTail: true,
    hasHorns: false,
    dangerous: true,
    domestic: false,

    largeAnimal: false,
    hasStripes: false,
    hasSpots: false,
    hasLongEars: false,
    hasLongNeck: false,
  },

  {
    id: 16,
    name: "Shark",
    image: "src/animals/shark.jpg",

    mammal: false,
    bird: false,
    reptile: false,
    fish: true,
    hasFur: false,
    hasWings: false,
    canFly: false,
    livesInWater: true,
    fourLegs: false,
    hasTail: true,
    hasHorns: false,
    dangerous: true,
    domestic: false,

    largeAnimal: true,
    hasStripes: false,
    hasSpots: false,
    hasLongEars: false,
    hasLongNeck: false,
  },

  {
    id: 17,
    name: "Dolphin",
    image: "src/animals/dolphin.jpg",

    mammal: true,
    bird: false,
    reptile: false,
    fish: false,
    hasFur: false,
    hasWings: false,
    canFly: false,
    livesInWater: true,
    fourLegs: false,
    hasTail: true,
    hasHorns: false,
    dangerous: false,
    domestic: false,

    largeAnimal: true,
    hasStripes: false,
    hasSpots: false,
    hasLongEars: false,
    hasLongNeck: false,
  },

  {
    id: 18,
    name: "Butterfly",
    image: "src/animals/butterfly.jpg",

    mammal: false,
    bird: false,
    reptile: false,
    fish: false,
    hasFur: false,
    hasWings: true,
    canFly: true,
    livesInWater: false,
    fourLegs: false,
    hasTail: false,
    hasHorns: false,
    dangerous: false,
    domestic: false,

    largeAnimal: false,
    hasStripes: false,
    hasSpots: true,
    hasLongEars: false,
    hasLongNeck: false,
  },
];

const marioCharacters = [
  {
    id: 1,
    name: "Mario",
    image: "src/mario/mario.png",

    human: true,
    male: true,
    female: false,
    royal: false,

    wearsHat: true,
    wearsCrown: false,
    wearsDress: false,
    hasMoustache: true,
    hasHair: true,
    blondeHair: false,
    brownHair: true,
    redHair: false,

    hasRed: true,
    hasGreen: false,
    hasBlue: true,
    hasPink: false,
    hasYellow: false,
    hasPurple: false,

    animalLike: false,
    hasShell: false,
    hasHorns: false,
    hasTail: false,
    hasMask: false,
    mushroomLike: false,
    isKong: false,
    ghost: false,
    villain: false,
  },

  {
    id: 2,
    name: "Bowser",
    image: "src/mario/bowser.png",

    human: false,
    male: true,
    female: false,
    royal: true,

    wearsHat: false,
    wearsCrown: false,
    wearsDress: false,
    hasMoustache: false,
    hasHair: true,
    blondeHair: false,
    brownHair: false,
    redHair: true,

    hasRed: true,
    hasGreen: true,
    hasBlue: false,
    hasPink: false,
    hasYellow: true,
    hasPurple: false,

    animalLike: true,
    hasShell: true,
    hasHorns: true,
    hasTail: true,
    hasMask: false,
    mushroomLike: false,
    isKong: false,
    ghost: false,
    villain: true,
  },

  {
    id: 3,
    name: "Bowser Jr.",
    image: "src/mario/bowser_jr.png",

    human: false,
    male: true,
    female: false,
    royal: true,

    wearsHat: false,
    wearsCrown: false,
    wearsDress: false,
    hasMoustache: false,
    hasHair: true,
    blondeHair: false,
    brownHair: false,
    redHair: true,

    hasRed: false,
    hasGreen: true,
    hasBlue: false,
    hasPink: false,
    hasYellow: true,
    hasPurple: false,

    animalLike: true,
    hasShell: true,
    hasHorns: false,
    hasTail: true,
    hasMask: false,
    mushroomLike: false,
    isKong: false,
    ghost: false,
    villain: true,
  },

  {
    id: 4,
    name: "Daisy",
    image: "src/mario/daisy.png",

    human: true,
    male: false,
    female: true,
    royal: true,

    wearsHat: false,
    wearsCrown: true,
    wearsDress: true,
    hasMoustache: false,
    hasHair: true,
    blondeHair: false,
    brownHair: true,
    redHair: false,

    hasRed: false,
    hasGreen: false,
    hasBlue: false,
    hasPink: false,
    hasYellow: true,
    hasPurple: false,

    animalLike: false,
    hasShell: false,
    hasHorns: false,
    hasTail: false,
    hasMask: false,
    mushroomLike: false,
    isKong: false,
    ghost: false,
    villain: false,
  },

  {
    id: 5,
    name: "Donkey Kong",
    image: "src/mario/donkey_kong.png",

    human: false,
    male: true,
    female: false,
    royal: false,

    wearsHat: false,
    wearsCrown: false,
    wearsDress: false,
    hasMoustache: false,
    hasHair: true,
    blondeHair: false,
    brownHair: true,
    redHair: false,

    hasRed: true,
    hasGreen: false,
    hasBlue: false,
    hasPink: false,
    hasYellow: true,
    hasPurple: false,

    animalLike: true,
    hasShell: false,
    hasHorns: false,
    hasTail: false,
    hasMask: false,
    mushroomLike: false,
    isKong: true,
    ghost: false,
    villain: false,
  },

  {
    id: 6,
    name: "Koopa Troopa",
    image: "src/mario/koopa_troopa.png",

    human: false,
    male: true,
    female: false,
    royal: false,

    wearsHat: false,
    wearsCrown: false,
    wearsDress: false,
    hasMoustache: false,
    hasHair: false,
    blondeHair: false,
    brownHair: false,
    redHair: false,

    hasRed: false,
    hasGreen: true,
    hasBlue: false,
    hasPink: false,
    hasYellow: true,
    hasPurple: false,

    animalLike: true,
    hasShell: true,
    hasHorns: false,
    hasTail: true,
    hasMask: false,
    mushroomLike: false,
    isKong: false,
    ghost: false,
    villain: false,
  },

  {
    id: 7,
    name: "Luigi",
    image: "src/mario/luigi.png",

    human: true,
    male: true,
    female: false,
    royal: false,

    wearsHat: true,
    wearsCrown: false,
    wearsDress: false,
    hasMoustache: true,
    hasHair: true,
    blondeHair: false,
    brownHair: true,
    redHair: false,

    hasRed: false,
    hasGreen: true,
    hasBlue: true,
    hasPink: false,
    hasYellow: false,
    hasPurple: false,

    animalLike: false,
    hasShell: false,
    hasHorns: false,
    hasTail: false,
    hasMask: false,
    mushroomLike: false,
    isKong: false,
    ghost: false,
    villain: false,
  },

  {
    id: 8,
    name: "Pauline",
    image: "src/mario/pauline.png",

    human: true,
    male: false,
    female: true,
    royal: false,

    wearsHat: true,
    wearsCrown: false,
    wearsDress: true,
    hasMoustache: false,
    hasHair: true,
    blondeHair: false,
    brownHair: true,
    redHair: false,

    hasRed: true,
    hasGreen: false,
    hasBlue: false,
    hasPink: false,
    hasYellow: false,
    hasPurple: false,

    animalLike: false,
    hasShell: false,
    hasHorns: false,
    hasTail: false,
    hasMask: false,
    mushroomLike: false,
    isKong: false,
    ghost: false,
    villain: false,
  },

  {
    id: 9,
    name: "Princess Peach",
    image: "src/mario/princess_peach.png",

    human: true,
    male: false,
    female: true,
    royal: true,

    wearsHat: false,
    wearsCrown: true,
    wearsDress: true,
    hasMoustache: false,
    hasHair: true,
    blondeHair: true,
    brownHair: false,
    redHair: false,

    hasRed: false,
    hasGreen: false,
    hasBlue: true,
    hasPink: true,
    hasYellow: false,
    hasPurple: false,

    animalLike: false,
    hasShell: false,
    hasHorns: false,
    hasTail: false,
    hasMask: false,
    mushroomLike: false,
    isKong: false,
    ghost: false,
    villain: false,
  },

  {
    id: 10,
    name: "Rosalina",
    image: "src/mario/rosalina.png",

    human: true,
    male: false,
    female: true,
    royal: true,

    wearsHat: false,
    wearsCrown: true,
    wearsDress: true,
    hasMoustache: false,
    hasHair: true,
    blondeHair: true,
    brownHair: false,
    redHair: false,

    hasRed: false,
    hasGreen: true,
    hasBlue: true,
    hasPink: false,
    hasYellow: false,
    hasPurple: false,

    animalLike: false,
    hasShell: false,
    hasHorns: false,
    hasTail: false,
    hasMask: false,
    mushroomLike: false,
    isKong: false,
    ghost: false,
    villain: false,
  },

  {
    id: 11,
    name: "Shy Guy",
    image: "src/mario/shy_guy.png",

    human: false,
    male: true,
    female: false,
    royal: false,

    wearsHat: false,
    wearsCrown: false,
    wearsDress: false,
    hasMoustache: false,
    hasHair: false,
    blondeHair: false,
    brownHair: false,
    redHair: false,

    hasRed: true,
    hasGreen: false,
    hasBlue: true,
    hasPink: false,
    hasYellow: false,
    hasPurple: false,

    animalLike: false,
    hasShell: false,
    hasHorns: false,
    hasTail: false,
    hasMask: true,
    mushroomLike: false,
    isKong: false,
    ghost: false,
    villain: false,
  },

  {
    id: 12,
    name: "Toad",
    image: "src/mario/toad.png",

    human: false,
    male: true,
    female: false,
    royal: false,

    wearsHat: false,
    wearsCrown: false,
    wearsDress: false,
    hasMoustache: false,
    hasHair: false,
    blondeHair: false,
    brownHair: false,
    redHair: false,

    hasRed: true,
    hasGreen: false,
    hasBlue: true,
    hasPink: false,
    hasYellow: false,
    hasPurple: false,

    animalLike: false,
    hasShell: false,
    hasHorns: false,
    hasTail: false,
    hasMask: false,
    mushroomLike: true,
    isKong: false,
    ghost: false,
    villain: false,
  },

  {
    id: 13,
    name: "Waluigi",
    image: "src/mario/waluigi.png",

    human: true,
    male: true,
    female: false,
    royal: false,

    wearsHat: true,
    wearsCrown: false,
    wearsDress: false,
    hasMoustache: true,
    hasHair: true,
    blondeHair: false,
    brownHair: true,
    redHair: false,

    hasRed: false,
    hasGreen: false,
    hasBlue: false,
    hasPink: false,
    hasYellow: false,
    hasPurple: true,

    animalLike: false,
    hasShell: false,
    hasHorns: false,
    hasTail: false,
    hasMask: false,
    mushroomLike: false,
    isKong: false,
    ghost: false,
    villain: true,
  },

  {
    id: 14,
    name: "Wario",
    image: "src/mario/wario.png",

    human: true,
    male: true,
    female: false,
    royal: false,

    wearsHat: true,
    wearsCrown: false,
    wearsDress: false,
    hasMoustache: true,
    hasHair: true,
    blondeHair: false,
    brownHair: true,
    redHair: false,

    hasRed: false,
    hasGreen: true,
    hasBlue: false,
    hasPink: false,
    hasYellow: true,
    hasPurple: true,

    animalLike: false,
    hasShell: false,
    hasHorns: false,
    hasTail: false,
    hasMask: false,
    mushroomLike: false,
    isKong: false,
    ghost: false,
    villain: true,
  },

  {
    id: 15,
    name: "Yoshi",
    image: "src/mario/yoshi.png",

    human: false,
    male: true,
    female: false,
    royal: false,

    wearsHat: false,
    wearsCrown: false,
    wearsDress: false,
    hasMoustache: false,
    hasHair: false,
    blondeHair: false,
    brownHair: false,
    redHair: false,

    hasRed: true,
    hasGreen: true,
    hasBlue: false,
    hasPink: false,
    hasYellow: false,
    hasPurple: false,

    animalLike: true,
    hasShell: false,
    hasHorns: false,
    hasTail: true,
    hasMask: false,
    mushroomLike: false,
    isKong: false,
    ghost: false,
    villain: false,
  },

  {
    id: 16,
    name: "Boo",
    image: "src/mario/boo.png",

    human: false,
    male: true,
    female: false,
    royal: false,

    wearsHat: false,
    wearsCrown: false,
    wearsDress: false,
    hasMoustache: false,
    hasHair: false,
    blondeHair: false,
    brownHair: false,
    redHair: false,

    hasRed: true,
    hasGreen: false,
    hasBlue: false,
    hasPink: false,
    hasYellow: false,
    hasPurple: false,

    animalLike: false,
    hasShell: false,
    hasHorns: false,
    hasTail: false,
    hasMask: false,
    mushroomLike: false,
    isKong: false,
    ghost: true,
    villain: true,
  },

  {
    id: 17,
    name: "Diddy Kong",
    image: "src/mario/diddy_kong.png",

    human: false,
    male: true,
    female: false,
    royal: false,

    wearsHat: true,
    wearsCrown: false,
    wearsDress: false,
    hasMoustache: false,
    hasHair: true,
    blondeHair: false,
    brownHair: true,
    redHair: false,

    hasRed: true,
    hasGreen: false,
    hasBlue: false,
    hasPink: false,
    hasYellow: true,
    hasPurple: false,

    animalLike: true,
    hasShell: false,
    hasHorns: false,
    hasTail: true,
    hasMask: false,
    mushroomLike: false,
    isKong: true,
    ghost: false,
    villain: false,
  },

  {
    id: 18,
    name: "King Boo",
    image: "src/mario/king_boo.png",

    human: false,
    male: true,
    female: false,
    royal: true,

    wearsHat: false,
    wearsCrown: true,
    wearsDress: false,
    hasMoustache: false,
    hasHair: false,
    blondeHair: false,
    brownHair: false,
    redHair: false,

    hasRed: true,
    hasGreen: false,
    hasBlue: true,
    hasPink: false,
    hasYellow: true,
    hasPurple: true,

    animalLike: false,
    hasShell: false,
    hasHorns: false,
    hasTail: false,
    hasMask: false,
    mushroomLike: false,
    isKong: false,
    ghost: true,
    villain: true,
  },
];